### ISSUE TITLE
command line not responding

### ISSUE THREAD

**Issue by vinthesun** [Eun/DisableMonitor#16] opened 2015-01-31 10:05 UTC
works fine via the menubar. when invoked via command line though, it starts (shows up in the command line) but does not respond in the terminal. Even though I tried all mentioned switches, it might be some silly mistake on my side...

OS X Yosemite, Mavericks
![bildschirmfoto 2015-01-31 um 11 03 03](https://cloud.githubusercontent.com/assets/10784291/5987676/c1f6cadc-a938-11e4-862e-86de53f65fb1.png)

**Comment by Eun** [comment] 2015-01-31 10:26
On Mavericks it works (for me). For Yosemite I will check it on Monday.

Silly question:
Did you copy the app in your `/Applications` folder?

What is the output of 

    ls -la /Applications/DisableMonitor.app/Contents/MacOS/DisableMonitor

**Comment by vinthesun** [comment] 2015-01-31 10:48
Yes, it is in the Applications folder, you can even see it appearing in the Mac status bar when invoked from the command line. It disappears from there when you do a `ctrl c`. It just does not output anything in the terminal.

The output is
`-rwxr-xr-x@ 1 Volker  staff  97576 30 Okt 10:57 /Applications/DisableMonitor.app/Contents/MacOS/DisableMonitor`

**Comment by Eun** [comment] 2015-01-31 15:20
Please try Version 1.9, since I updated the usage a while ago.

**Comment by Eun** [comment] 2015-02-01 11:57
Confirmed bug in 1.8, Resolved in 1.9

**Closed by Eun** 2015-02-01 11:57 UTC
Labels: bug

**Comment by vinthesun** [comment] 2015-02-02 16:08
Great, that works perfect. Many Thanks.
